#!/bin/bash
# WHEEE Protocol Setup Script
# Run this in your project directory to initialize WHEEE Protocol

echo "🚀 Setting up WHEEE Protocol..."

# Check if we're in a git repo
if [ ! -d ".git" ]; then
    echo "⚠️  Not a git repository. Initializing..."
    git init
fi

# 1. Create directory structure
echo "📁 Creating directory structure..."
mkdir -p .planning/phases
mkdir -p project
mkdir -p architecture
mkdir -p tools
mkdir -p tests
mkdir -p .tmp
mkdir -p docs/content

# 2. Create project memory files
echo "📝 Creating project memory files..."

# Create project/README.md
cat > project/README.md <<'EOF'
# Project Memory Files

See WHEEE Protocol documentation for file purposes.

- `task_plan.md` - Phases, goals, checklists
- `findings.md` - Research discoveries
- `progress.md` - Progress tracker
- `process-journal.md` - Development journey
- `gemini.md` - Data schemas, behavioral rules
- `architecture.md` - System architecture
- `changelog.md` - Version history
- `errors.md` - Error logs
EOF

# Create empty memory files
touch project/task_plan.md
touch project/findings.md
touch project/progress.md
touch project/process-journal.md
touch project/gemini.md
touch project/architecture.md
touch project/changelog.md
touch project/errors.md

# 3. Create .planning structure
echo "📋 Creating GSD planning structure..."
cat > project/wheee-config.json <<'EOF'
{
  "version": "1.3.0",
  "modules": {
    "agent-turbo": false,
    "multi-agent": false,
    "design-mode": false
  }
}
EOF

cat > .planning/PROJECT.md <<'EOF'
# Project Overview

[Describe your project here. What is the main goal?]
EOF

cat > .planning/REQUIREMENTS.md <<'EOF'
# Project Requirements

## Core Requirements
- [ ] Initial setup and protocol implementation

## Future Requirements
- [ ] ...
EOF

cat > .planning/ROADMAP.md <<'EOF'
# Project Roadmap

## Phase 0: Initialization (Mandatory)
- [x] Initial protocol setup (GSD + B.L.A.S.T.)

## Phase 1: Blueprint
- [ ] Answer 5 Discovery Questions
- [ ] Define Data Schema
- [ ] Architect System Structure
EOF

cat > .planning/STATE.md <<'EOF'
# Project State

**Current Phase:** Phase 0: Initialization
**Status:** Completed
**Mode:** S (Initial Assessment)

---
*Generated by WHEEE Protocol v1.3.0*
EOF

# 3.1 Initialize first GSD Phase (Mandatory)
echo "🏗️  Initializing mandatory GSD Phase 0..."
mkdir -p .planning/phases/00-initialization
cat > .planning/phases/00-initialization/00-01-PLAN.md <<'EOF'
# Phase 0.1: Initialization Plan

## Goal
Establish the project foundation using the WHEEE Protocol (GSD + B.L.A.S.T.).

## Steps
1. [x] Run `wheee init` to create directory structure.
2. [x] Initialize project memory files in `project/`.
3. [x] Set up GSD planning structure in `.planning/`.
4. [ ] Verify setup with `wheee audit`.

## Verification Criteria
- [ ] All core directories exist.
- [ ] `wheee audit` passes with zero failures.
EOF

cat > .planning/phases/00-initialization/00-01-SUMMARY.md <<'EOF'
# Phase 0.1: Initialization Summary

## Results
- Directory structure created.
- Mandatory GSD/BLAST files initialized.
- Git hooks and automation tools configured.

## Next Step
Proceed to Phase 1: Blueprint.
EOF

# 4. Create .env.example
echo "🔐 Creating .env.example..."
cat > .env.example <<'EOF'
# Environment Variables Template
# Copy this file to .env and fill in your actual values
# NEVER commit .env to version control

# Add your environment variables here
# Example:
# API_KEY=your_api_key_here
# DATABASE_URL=your_database_url_here
EOF

# 5. Update .gitignore
echo "📝 Updating .gitignore..."
if [ ! -f .gitignore ]; then
    cat > .gitignore <<'EOF'
# Environment Variables
.env
.env.local
.env.*.local

# Temporary Files
.tmp/
tmp/
*.tmp

# Dependencies
node_modules/
__pycache__/
*.pyc

# Build outputs
dist/
build/
*.log

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db
EOF
else
    # Append if .gitignore exists
    if ! grep -q ".env" .gitignore; then
        echo "" >> .gitignore
        echo "# WHEEE Protocol" >> .gitignore
        echo ".env" >> .gitignore
        echo ".tmp/" >> .gitignore
    fi
fi

# 6. Install git hooks
echo "🪝 Installing git hooks..."
if [ -d ".git/hooks" ]; then
    cp tools/automation/git-hooks/post-commit .git/hooks/post-commit 2>/dev/null
    cp tools/automation/git-hooks/post-merge .git/hooks/post-merge 2>/dev/null
    chmod +x .git/hooks/post-commit 2>/dev/null
    chmod +x .git/hooks/post-merge 2>/dev/null
    echo "  ✅ Git hooks installed"
else
    echo "  ⚠️  .git/hooks not found, skipping"
fi

# 7. Make automation scripts executable
echo "🔧 Making scripts executable..."
chmod +x tools/automation/*.js 2>/dev/null

echo ""
echo "✅ WHEEE Protocol setup complete!"
echo ""
echo "📋 Next steps:"
echo "   1. Fill in .planning/PROJECT.md with your project details"
echo "   2. Answer Discovery Questions (see PROTOCOL.md)"
echo "   3. Define data schema in project/gemini.md"
echo "   4. Design architecture in project/architecture.md"
echo "   5. Start building!"
echo ""
echo "📖 Read PROTOCOL.md for complete workflow guide"
