name: Self-Healing Build

on:
  pull_request:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  self-heal-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Self-Heal Build Issues
        run: |
          echo "🔧 Running self-healing build system..."
          node tools/automation/self-heal-build.js --fix-all || true
          echo "✅ Self-healing complete"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint || true
      
      - name: Run tests
        run: npm test
      
      - name: Build project
        run: npm run build
      
      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7
